### ISSUE TITLE
Fehler bei HTTPS Erkennung - eigentlich ungültiges Zertifikat auf nicht kanonischer URL

### ISSUE THREAD

**Issue by volschin** [netzbegruenung/green-spider#125]
Für die Seite https://gruene-xhain.de/ wird kein HTTPS erkannt. Ist aber vorhanden.
https://green-spider.netzbegruenung.de/sites/https%3A%2F%2Fgruene-xhain.de%2F

**Comment by patrickhanft** [comment]
@marians spannende Frage, warum die Erkennung so ausfällt, wie sie ausfällt.

Die Website ist momentan übrigens ein guter Testcase für das in #123 diskutierte Problem "AAAA-Record aber nicht via v6 erreichbar". Vielleicht steht das indirekt irgendwie in Zusammenhang hier …

**Comment by marians** [comment]
@volschin Danke fürs Melden hier. Ich habe mir das genauer angesehen und festgestellt, dass das Problem die Verkettung mehrerer Tests nacheinander ist, und die Tatsache, wie unser Spider aktuell mit deren Ergebnissen umgeht. Die Site https://gruene-xhain.de ist natürlich in Ordnung.

Was passiert:

Der Spider erstellt zunächst vier URL-Varianten, nämlich mit HTTP und HTTPS für die Domain mit `www.` davor und ohne `www.` davor (weil teilweise von Menschen immer noch angenommen wird, dass eine Web-URL mit  `www.` beginnen muss.

Bei `https://www.gruene-xhain.de/` ist es tatsächlich so, dass es kein gültiges Zertifikat gibt. Siehe https://www.ssllabs.com/ssltest/analyze.html?d=www.gruene-xhain.de

Weil es kein gültiges Zertifikat gibt, kann von dieser URL auch nicht auf die kanonische URL `https://gruene-xhain.de` umgeleitet werden, wie es bei `http://gruene-xhain.de` und `http://www.gruene-xhain.de` der Fall ist.

Ein solches Problem sollte meines Erachtens eher unter `Verschiedene URL-Varianten werden auf eine einzige umgeleitet` aufgezeigt und bemängelt werden.

Für Euch wäre es eine Möglichkeit, für `www.gruene-xhain.de` ein zusätzliches, kostenloses Zertifikat über Let's Encrypt zu beziehen.

**Comment by volschin** [comment]
Danke für die Erläuterungen. Die Problembeschreibung des Certificate Mismatch und auf welcher URL-Variante er geschieht sollte definitiv verbessert werden, da das sonst durch niemand nachvollziehbar ist.

**Comment by marians** [comment]
Hierzu sollte https://github.com/netzbegruenung/green-spider-webapp/pull/60 Abhilfe schaffen.
