### ISSUE TITLE
Probleme mit TLS-Zertifikaten sollten im Detail erfasst werden

### ISSUE THREAD

**Issue by marians** [netzbegruenung/green-spider#13]
Wir sollten Details zu HTTPS-Zertifikaten erfassen und Aussagen darüber treffen können,

- wann ein Zertifikat abläuft
- ob ein Zertifikat für den Hostnamen gültig ist
- ob ein Zertifikat von einer allgemein vertrauenswürdigen CA stammt
  - ob das Zertifikat von einer CA stammt, die von Chrome (demnächst) als nicht vertrauenswürdig erachtet wird (https://security.googleblog.com/2018/03/distrust-of-symantec-pki-immediate.html)
- ob die CA chain komplett ist

**Comment by marians** [comment]
So kann das Server-Zertifikat einfachausgelesen werden:

https://stackoverflow.com/questions/49132025/ssl-get-server-certificate-for-sites-with-sni-server-name-indication/49132495#49132495

**Comment by patrickhanft** [comment]
ggf. wäre ja auch der Einsatz von `sslyze` (macht auch json-output) interessant?

**Comment by marians** [comment]
sslyze sieht gut aus, danke! Besonders, weil es analysiert, in welchem System eine CA (root) als vertrauenswürdig angesehen wird. Jedenfalls habe ich es so verstanden. Dazu auch https://nabla-c0d3.github.io/blog/2018/01/16/trust-stores-observatory/

**Comment by marians** [comment]
In https://github.com/netzbegruenung/green-spider/pull/70 ist ein neuer check enthalten, der mit `pyOpenSSL` arbeitet.

Darin ist noch nicht enthalten:

- Komplettheit der CA Chain prüfen
- Vertrauenswürdigkeit der Issuer CA prüfen

Die Überprüfung der Gültigkeit des Hostnamen wird schon über Exceptions in einem anderen Test (`url_reachability`) erfasst. Sofern das Zertifikat nicht zum Hostnamen passt, wir die URL nicht als erreichbar gewertet und die entsprechende Fehlermeldung wird erfasst.

**Comment by marians** [comment]
https://github.com/netzbegruenung/green-spider-webapp/pull/60 ist ein Schritt in die Richtung dieses Issues.

**Comment by marians** [comment]
Schließe das Issue, in der Annahme, dass die aktuell gezeigten Informationen erst mal ausreichen.
