### ISSUE TITLE
Website missing, please add

### ISSUE THREAD

**Issue by dstankewitz** [netzbegruenung/green-spider#193]
Our website is not listed in the green spider. Could you please add it, sowe can see how to make it better? The website is https://gruene-frankfurtwest.de/startseite/ and we are Ortsbeirat 5 Frankfurt West in Frankfurt / MAin.

**Comment by marians** [comment]
Hallo! Bitte füge die Site in https://github.com/netzbegruenung/green-directory ein. Oder sag bescheid, falls es jemand anderes für Euch machen soll. Danke!
