### ISSUE TITLE
Überprüfung der Schriftarten sollte GrueneType statt Arvo finden

### ISSUE THREAD

**Issue by marians** [netzbegruenung/green-spider#341]
Momentan prüfen wir, ob die Schriftart Arvo verwendet wird. Falls nicht zeigen wir das an:

![Image](https://github.com/netzbegruenung/green-spider/assets/273727/27bc8f84-c1cf-44e1-81a7-ba6378a29020)

Inzwischen gilt ein neuer Style Guide und die Arvo wird nicht mehr empfohlen. Stattdessen ist `GrueneType` die empfohlene Schrift für Überschriften.

**Comment by TheBendingRodriguez** [comment]
Hi, irgendwelche Ideen, wie man das prüfen könnte? Habe gesehen, dass die Checks des Spyders in Python geschrieben sind. In der Doku der Webfonts unter https://github.com/netzbegruenung/webfonts steht, dass man die Schriften über <link rel="stylesheet" type="text/css" href="https://netzbegruenung.github.io/webfonts/style.css"> in den Head einfügen muss. Das kann man ja relativ easy prüfen, indem man sich den html-code per request zieht und schaut ob er den Link zu den Webfonts enthält, oder?

**Comment by marians** [comment]
HIer ist die Änderung im Spider: https://github.com/netzbegruenung/green-spider/pull/342

Und hier im Front-End: https://git.verdigado.com/Netzbegruenung/green-spider-webapp/pulls/12

Die Änderung wird in den nächsten Tagen effektiv.

**Comment by marians** [comment]
Erledigt
